name: ml-ids-api-client
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - boto3=1.10.30
  - click=7.0
  - numpy=1.17.2
  - mypy=0.750
  - pandas=0.25.2
  - pip=19.2.3
  - pylint=2.4.4
  - pytest=5.2.1
  - pytest-runner=5.1
  - python=3.7.3
  - requests=2.22.0
  - responses=0.10.6
  - setuptools=41.6.0
  - tabulate=0.8.6
  - pip:
    - h5py==2.10.0
    - tables==3.6.1
